# Generated by Django 3.0.9 on 2020-08-10 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Alumno', '0004_auto_20200803_1639'),
        ('Sucursal', '0002_auto_20200728_1440'),
        ('Nivel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('nota', models.IntegerField(blank=True, default=0)),
                ('alumno_id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.Alumno')),
                ('nivel_id_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nivel.Nivel')),
                ('sucursal_id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sucursal.Sucursal')),
                ('usuario_id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
