# Generated by Django 3.0.8 on 2020-08-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='nota',
            field=models.IntegerField(default=0),
        ),
    ]
