# Generated by Django 3.0.9 on 2020-08-11 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='nota',
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('nota', models.IntegerField(default=0)),
                ('inscripcion_id_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inscripcion.Inscripcion')),
            ],
        ),
    ]
