# Generated by Django 3.0.8 on 2020-07-28 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nivel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catedratico',
            fields=[
                ('id_catedratico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('dpi', models.CharField(max_length=13, unique=True)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('catedratico_id_catedratico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contrato.Catedratico')),
                ('nivel_id_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nivel.Nivel')),
            ],
        ),
    ]
