# Generated by Django 3.0.8 on 2020-07-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('razon_social', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=125)),
                ('correo', models.CharField(max_length=125)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
    ]
