# Generated by Django 3.0.8 on 2020-07-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idtipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=125)),
                ('password', models.CharField(max_length=45)),
                ('tipo_usuario_idtipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.TipoUsuario')),
            ],
        ),
    ]
