# Generated by Django 3.0.8 on 2020-07-28 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_auto_20200728_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
