# Generated by Django 3.0.8 on 2020-08-11 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_usuario_sucursar_id_sucursal'),
        ('Usuario', '0003_auto_20200728_1505'),
    ]

    operations = [
    ]
