# Generated by Django 3.0.9 on 2020-08-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0003_auto_20200803_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
    ]
