# Generated by Django 3.0.8 on 2020-07-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_nivel', models.CharField(max_length=45)),
                ('grado_id_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nivel.Grado')),
            ],
        ),
    ]
